### ISSUE TITLE
timeago 1.0.12 refuses to install on Windows 10

### ISSUE THREAD

**Issue by AlexFlipnote** [hustcc/timeago#29]
```py
C:\WINDOWS\system32>pip install timeago --upgrade
Collecting timeago
  Using cached https://files.pythonhosted.org/packages/70/c7/3a1ccd78d542e592534f4c74e63ead33d5f11977b0e26d061e022ed285ed/timeago-1.0.12.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'c:\python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\AlexFlipnote\\AppData\\Local\\Temp\\pip-install-6k63qzau\\timeago\\setup.py'"'"'; __file__='"'"'C:\\Users\\AlexFlipnote\\AppData\\Local\\Temp\\pip-install-6k63qzau\\timeago\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\AlexFlipnote\AppData\Local\Temp\pip-install-6k63qzau\timeago\pip-egg-info'
         cwd: C:\Users\AlexFlipnote\AppData\Local\Temp\pip-install-6k63qzau\timeago\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\AlexFlipnote\AppData\Local\Temp\pip-install-6k63qzau\timeago\setup.py", line 12, in <module>
        long_description = readme(),
      File "C:\Users\AlexFlipnote\AppData\Local\Temp\pip-install-6k63qzau\timeago\setup.py", line 7, in readme
        return f.read()
      File "c:\python37\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 805: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Current Python version: Python 3.7.4
Tried versions: 3.7.6, 3.8.1
OS: Windows 10 Pro

Note: It does work to install it on my **Debian 8.10** server, as a side-note.

**Comment by lolobosse** [comment]
Ok, I can understand the error. But I need to reproduce it on a windows
computer to fix it.

Let me few hours...

It's not about 1.0.12 btw: it's from the moment where I changed the
`setup.py` I guess that 1.0.7 would work (in case it helps for you because
you need to make it work asap :smile:)

Le dim. 5 janv. 2020 à 23:44, AlexFlipnote <notifications@github.com> a
écrit :

**Comment by AlexFlipnote** [comment]
I use 1.0.10 which is the last version to work on Windows actually. Don't have to make it work asap, but would be nice to cases where I debug on Windows machine and not on my server 😊

**Comment by lolobosse** [comment]
Is it working with `timeago 1.0.13`?

**Comment by AlexFlipnote** [comment]
```
C:\WINDOWS\system32>pip install timeago
Collecting timeago
  Using cached https://files.pythonhosted.org/packages/57/68/513d00d481bc8989a75a0a817ac199f9e0ddb769209baab694f5d035a0e4/timeago-1.0.13.tar.gz
Installing collected packages: timeago
    Running setup.py install for timeago ... done
Successfully installed timeago-1.0.13
```
Yupp, it works to install it on Windows now and to use in Python scripts, thank you. ❤️

**Comment by lolobosse** [comment]
Very nice! Thanks for reporting :pray:

Le lun. 13 janv. 2020 à 20:22, AlexFlipnote <notifications@github.com> a
écrit :
